version: '3.9'

services:
  frontend:
    build:
      context: ./elections-frontend  # Points to the elections-frontend directory
      dockerfile: Dockerfile
      target: frontend-runtime
    ports:
      - "3000:80"
    volumes:
      - ./elections-frontend:/app
    environment:
      - PORT=3000

  backend:
    build:
      context: ./elections-backend  # Points to the correct directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://oege.ie.hva.nl:3306/zeijky1?useSSL=true
      - SPRING_DATASOURCE_USERNAME=eijky1
      - SPRING_DATASOURCE_PASSWORD=dDeaGhAyipadFk.t
      - SERVER_PORT=8080

