package com.election.electionsbackend.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "candidates")
@JsonIgnoreProperties
@Getter
@Setter
@NoArgsConstructor
public class Candidate {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "candidate_id")
    private int candidateID;

    @Column(name = "kandidaat_nummer", unique = true)
    private Integer kandidaatNummer;

    @Column(name = "kandidaat_initialen")
    private String kandidaatInitialen;

    @Column(name = "kandidaat_voornaam")
    private String kandidaatVoornaam;

    @Column(name = "kandidaat_tussenvoegsel")
    private String kandidaatTussenvoegsel;

    @Column(name = "kandidaat_achternaam")
    private String kandidaatAchternaam;

    @Column(name = "kandidaat_woonplaats")
    private String kandidaatWoonplaats;

    @Column(name = "kandidaat_geslacht")
    private Character kandidaatGeslacht;

    // Constructors, getters, and setters will be generated by Lombok
}
